#if !canImport(ObjectiveC)
import XCTest

extension TargetBTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TargetBTests = [
        ("test_targetB", test_targetB),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TargetBTests.__allTests__TargetBTests),
    ]
}
#endif
