#if !canImport(ObjectiveC)
import XCTest

extension TargetA1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TargetA1Tests = [
        ("test_targetA1", test_targetA1),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TargetA1Tests.__allTests__TargetA1Tests),
    ]
}
#endif
